name: Merge Branches

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (for XML parsing)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Step 3: Install XML parser and other dependencies
      - name: Install dependencies
        run: |
          npm install xml2js

      # Step 4: Parse XML file and extract branch names
      - name: Parse XML file and get branches
      - uses: actions/github-script@v7  
      id: branches
        with:
          script: |
          const fs = require('fs');
          const xml2js = require('xml2js');

          const xmlFilePath = './branches.xml';
          const branches = [];

          fs.readFile(xmlFilePath, 'utf8', (err, data) => {
            if (err) {
              console.error('Error reading XML file:', err);
              process.exit(1);
            }

            xml2js.parseString(data, (err, result) => {
              if (err) {
                console.error('Error parsing XML:', err);
                process.exit(1);
              }

              const branchList = result.branches.branch;
              branchList.forEach(branch => {
                branches.push(branch[0]);
              });

              // Set the branches as output to be used in the next steps
              console.log(`Branches to merge: ${branches.join(', ')}`);
              core.setOutput('branches', branches.join(', '));
            });
          });

      # Step 5: Merge branches into target branch (e.g., 'main')
      - name: Merge branches
        run: |
          branches="${{ steps.branches.outputs.branches }}"
          target_branch="main"  # Change to your target branch
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          for branch in $(echo $branches | tr "," "\n")
          do
            git fetch origin $branch
            git checkout $target_branch
            git merge --no-ff $branch -m "Merging $branch into $target_branch"
            git push origin $target_branch
          done
