name: slack_notification
on:
  workflow_dispatch:
jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.INTERMEDIATE_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name "mamoanwar97-procore"
          git config --global user.email "mahmoud.m.anwar@procore.com"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install xmltodict
          pip install requests

      - name: Run Python script
        env:
          GH_TOKEN: ${{ secrets.INTERMEDIATE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.INTERMEDIATE_TOKEN }}
          SLACK_HOOK_URL: ${{ secrets.SLACK_HOOK_URL }}
        run: python slack_notify.py