name: Python Script Workflow

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install npm dependencies
        run: npm install

      - name: Create collection branch if not exists
        run: |
          if git show-ref --verify --quiet refs/heads/translations-collection; then
            git checkout translations-collection
          else
            git checkout -b translations-collection
          fi

      - uses: actions/github-script@v7
        env:
          FIRST_NAME: Mona
          LAST_NAME: Octocat
        with:
          script: |
            const { default: printStuff } = await import('${{ github.workspace }}/node.js')
            await printStuff()
